### ISSUE TITLE
Undefined is not an object (evaluating PropTypes.bool)

### ISSUE THREAD

**Issue by jlf123** [nulrich/RCTAutoComplete#62]
Getting this error when trying to run my react-native app in a simulator.
<img width="327" alt="screen shot 2017-11-17 at 1 16 39 pm" src="https://user-images.githubusercontent.com/13322508/32964718-b70da2ea-cb99-11e7-9440-cb90d973b63f.png">

**Comment by AmyNgithub** [comment]
Me too.

**Comment by EstebanErcole** [comment]
any updates?

**Comment by eballeste** [comment]
this is because the version in npm is outdated, doesn't have the latest fixes pushed by @riccardopiola in https://github.com/nulrich/RCTAutoComplete/pull/61. 

as a workaround, you can install this module directly from the master branch using:
`npm install github:nulrich/RCTAutoComplete --save`

@nulrich, could you push a new release to npm with the latest fixes?

**Comment by nulrich** [comment]
Sorry for the delay. I just published a new version on npm.

@eballeste Thanks for the workaround.
